/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddDialog: typeof import('./src/components/AddDialog.vue')['default']
    AddEditSeriesDialog: typeof import('./src/components/library/AddEditSeriesDialog.vue')['default']
    AddEditUserBookDialog: typeof import('./src/components/library/AddEditUserBookDialog.vue')['default']
    AppCard: typeof import('./src/components/AppCard.vue')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('primevue/card')['default']
    Carousel: typeof import('primevue/carousel')['default']
    Column: typeof import('primevue/column')['default']
    ConfirmationDialog: typeof import('./src/components/ConfirmationDialog.vue')['default']
    CustomDatePicker: typeof import('./src/components/CustomDatePicker.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Fieldset: typeof import('primevue/fieldset')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    IconField: typeof import('primevue/iconfield')['default']
    Image: typeof import('primevue/image')['default']
    ImageButton: typeof import('./src/components/ImageButton.vue')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Menu: typeof import('primevue/menu')['default']
    Menubar: typeof import('primevue/menubar')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    OfficeButton: typeof import('./src/components/OfficeButton.vue')['default']
    OfficeIconButton: typeof import('./src/components/OfficeIconButton.vue')['default']
    Panel: typeof import('primevue/panel')['default']
    Password: typeof import('primevue/password')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RefreshComponent: typeof import('./src/components/RefreshComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SeriesBook: typeof import('./src/components/library/SeriesBook.vue')['default']
    SeriesCarusel: typeof import('./src/components/library/SeriesCarusel.vue')['default']
    SeriesCaruselInfoDialog: typeof import('./src/components/library/SeriesCaruselInfoDialog.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheMenu: typeof import('./src/components/TheMenu.vue')['default']
    TheMenuLibrary: typeof import('./src/components/library/TheMenuLibrary.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
    UserBookLarge: typeof import('./src/components/library/UserBookLarge.vue')['default']
    UserBookSmall: typeof import('./src/components/library/UserBookSmall.vue')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
